
class IntegrationRules:
    USE_CANONICAL_FIELD_STATE = True
    ENABLE_PONYTAIL_GUARDRAILS = True
    REQUIRE_HUMAN_REVIEW_FOR_PESTICIDES = True
    ALLOW_DIRECT_TOOL_RECOMMENDATIONS = False
    ENABLE_TENANT_RAG_ISOLATION = True
