"""Canonical soil contracts shared by producers and governed consumers."""

from .observation import (
    SOIL_OBSERVATION_CONTRACT_VERSION,
    SoilObservation,
    SoilObservationQuality,
    SoilObservationSource,
)
from .profile import (
    SOIL_PROFILE_CONTRACT_VERSION,
    SoilEvidenceClass,
    SoilEvidenceLevel,
    SoilLayer,
    SoilModelInputs,
    SoilProfileSnapshot,
    SoilProfileStatus,
    SoilPropertyValue,
    SoilQualityGate,
    canonical_soil_profile_hash,
    validate_soil_profile_snapshot,
)

__all__ = [
    "SOIL_OBSERVATION_CONTRACT_VERSION",
    "SoilObservation",
    "SoilObservationQuality",
    "SoilObservationSource",
    "SOIL_PROFILE_CONTRACT_VERSION",
    "SoilEvidenceClass",
    "SoilEvidenceLevel",
    "SoilLayer",
    "SoilModelInputs",
    "SoilProfileSnapshot",
    "SoilProfileStatus",
    "SoilPropertyValue",
    "SoilQualityGate",
    "canonical_soil_profile_hash",
    "validate_soil_profile_snapshot",
    "SoilUseDecision",
    "validate_soil_use",
    "LOW_RISK_USES",
    "MEDIUM_RISK_USES",
    "HIGH_RISK_USES",
    "EvidenceOrigin",
    "SoilGridsLayerSummary",
    "SoilGridsSpatialProduct",
    "SamplingCandidate",
    "SamplingPlanRequest",
    "SamplingPoint",
    "SamplingPlan",
    "HydraulicValue",
    "SoilHydraulicLayer",
    "SoilHydraulicProfile",
    "IrrigationWaterSample",
    "IrrigationWaterProfile",
]

from .p1 import (
    EvidenceOrigin,
    HydraulicValue,
    IrrigationWaterProfile,
    IrrigationWaterSample,
    SamplingCandidate,
    SamplingPlan,
    SamplingPlanRequest,
    SamplingPoint,
    SoilGridsLayerSummary,
    SoilGridsSpatialProduct,
    SoilHydraulicLayer,
    SoilHydraulicProfile,
)
from .p2 import (
    BareSoilComposite,
    BareSoilCompositeRequest,
    BareSoilScene,
    SalinityAssessmentProduct,
    SalinityAssessmentRequest,
    SalinityZoneAssessment,
    SalinityZoneEvidence,
    TerrainDerivativesProduct,
    TerrainRequest,
    TextureCalibrationSample,
    TextureFeatureVector,
    TextureProbabilityProduct,
    TextureProbabilityRequest,
    TextureZoneProbability,
)
from .use_policy import (
    HIGH_RISK_USES,
    LOW_RISK_USES,
    MEDIUM_RISK_USES,
    SoilUseDecision,
    validate_soil_use,
)

__all__ += [
    "BareSoilScene",
    "BareSoilCompositeRequest",
    "BareSoilComposite",
    "TerrainRequest",
    "TerrainDerivativesProduct",
    "TextureFeatureVector",
    "TextureCalibrationSample",
    "TextureProbabilityRequest",
    "TextureZoneProbability",
    "TextureProbabilityProduct",
    "SalinityZoneEvidence",
    "SalinityAssessmentRequest",
    "SalinityZoneAssessment",
    "SalinityAssessmentProduct",
]
from .p3 import (
    AnalogFieldCandidate,
    AnalogFieldProduct,
    AnalogFieldRequest,
    AnalogPropertyEstimate,
    DrainageAssessmentProduct,
    DrainageAssessmentRequest,
    MobileImageQuality,
    MobileSoilImageRequest,
    ReclamationAssessmentProduct,
    ReclamationAssessmentRequest,
    ReclamationEconomicsProduct,
    ReclamationEconomicsRequest,
    ReclamationScenario,
    SoilVisualObservation,
    SoilVisualPrediction,
)

__all__ += [
    "MobileImageQuality",
    "SoilVisualPrediction",
    "MobileSoilImageRequest",
    "SoilVisualObservation",
    "AnalogFieldCandidate",
    "AnalogFieldRequest",
    "AnalogPropertyEstimate",
    "AnalogFieldProduct",
    "DrainageAssessmentRequest",
    "DrainageAssessmentProduct",
    "ReclamationAssessmentRequest",
    "ReclamationAssessmentProduct",
    "ReclamationEconomicsRequest",
    "ReclamationScenario",
    "ReclamationEconomicsProduct",
    "ApprovalRequirement",
    "SoilActionPolicy",
    "SoilActionEvaluation",
    "SoilExecutionRecord",
    "SoilVerificationRecord",
    "SoilOutcomeRecord",
    "SoilLearningAttribution",
]

from .p4 import (
    ApprovalRequirement,
    SoilActionEvaluation,
    SoilActionPolicy,
    SoilExecutionRecord,
    SoilLearningAttribution,
    SoilOutcomeRecord,
    SoilVerificationRecord,
)
