#!/usr/bin/env python3
"""Build a deterministic direct-dependency bundle for audit/review.

The output is intentionally labelled DIRECT. It is not a transitive lock. A true
transitive lock must be produced by a resolver (for example pip-tools) in connected CI
or in the final container build context.
"""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SERVICES = ROOT / "services"
OUT = ROOT / "requirements.services.direct.lock"


def meaningful(line: str) -> str:
    return line.split("#", 1)[0].strip()


def iter_req_files() -> list[Path]:
    return sorted(SERVICES.glob("*/requirements*.txt")) + sorted(SERVICES.glob("*/*/requirements*.txt"))


def build() -> str:
    chunks = [
        "# SAHOOL service direct dependency lock bundle",
        "# GENERATED by scripts/ci/build_service_dependency_bundle.py",
        "# Scope: direct service requirements only; not a transitive resolver output.",
        "# Use scripts/ci/compile_transitive_service_locks.sh in connected CI for true transitive locks.",
        "",
    ]
    for req_file in iter_req_files():
        rel = req_file.relative_to(ROOT)
        chunks.append(f"# --- {rel} ---")
        lines = []
        for raw in req_file.read_text(encoding="utf-8", errors="ignore").splitlines():
            req = meaningful(raw)
            if req and not req.startswith("-") and not req.startswith("--"):
                lines.append(req)
        chunks.extend(lines or ["# no direct dependencies"])
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = build()
    if args.check:
        old = OUT.read_text(encoding="utf-8") if OUT.exists() else None
        if old != content:
            raise SystemExit("Direct dependency bundle drift detected; run scripts/ci/build_service_dependency_bundle.py")
        print("direct_dependency_bundle_check_ok")
        return
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
