"""Slice C brain rows. argv: <root> <guard_sha> <debug_log_sha>. No invisible marks (the bidi guard counts them)."""
import pathlib, sys

root = pathlib.Path(sys.argv[1])
G = sys.argv[2]
L = sys.argv[3]
EV = "certification/evidence/railway_live_config_20260930.json"

ROWS = f"""| PRODUCTION-DEPLOYS-FROM-MAIN-WITHOUT-CI-GATE-01 | **أولويّة: حرِج.** خدماتُ الإنتاج المبنيّة من المستودع تُنشَر من `main` و`checkSuites:false`: Railway لا ينتظر CI، فالدمجُ يبلغ الإنتاج في ثوانٍ (#1112 بلغ واجهة الإنتاج 14:38:45Z). وكان فحصُ صحّة platform وauth في الإنتاج `/healthz` فيُقِرّ نشراً لا يعمل. | railway/production | `{EV}` (`production_gate`) | **open** (2026-09-30): نُفِّذ بقرار المالك جزءٌ بلا نشر — فحصُ الصحّة `/readyz` على platform وauth-main وauth في الإنتاج (موجودٌ في فروعها المنشورة). **الباقي في اللوحة:** Wait for CI (لا أداةَ MCP تضبطه دون إعادة ربط المصدر وبناء كلّ البيئات). CI على `main` أخضر (32/32 · 28/28) فلن يحجب صامتاً. ثمّ فرعُ إنتاجٍ منفصل. |
| PLATFORM-DEPLOYED-FROM-STALE-BRANCHES-UNPATCHED-PYJWT-01 | **أولويّة: مهمّ.** `sahool-platform` لا يُنشَر من `main` في أيّ بيئة: staging من `deploy/sahool-platform-db-ready-eb6da9df` (متأخّرٌ 4 التزامات في مساراته)، والإنتاج من `deploy/sahool-staging-fa92a1f7` (متأخّرٌ 24). كلاهما يثبّت PyJWT 2.13.0 و`main` على 2.14.0 (CVE-2026-102274). فأيّ إصلاحٍ يُدمَج يبلغ الإنتاج بعد أسابيع — حقيقةٌ واحدة (أين الإنتاج) تحدّد أثرَ كلّ دمج. | railway/platform | `{EV}` (`platform_branch_drift`) · `services/sahool-platform/api/requirements.txt` | **open** (2026-09-30): قرارُ المالك — النقلُ إلى `main`، staging أوّلاً ثمّ الإنتاج، بعد بوّابة الإنتاج. |
| DECISION-SERVICE-STAGING-BEHIND-TENANT-BOUNDARY-FIXES-01 | **أولويّة: مهمّ.** **الشيفرةُ المنشورة** لـdecision-service في staging هي `eff473aa` (#1080، إعادةُ نشرٍ جماعيّة 2026-09-28)؛ فينقصها `7059d0dc` (#1085) و`63727907` (#1086، ومعه الهجرة 034). **هذا ما دُفِع لا ما طُبِّق:** حالةُ الهجرات في القاعدة لم تُقرأ (صفّ `MIGRATION-STATE-IN-PRODUCTION-IS-UNREAD-01`)، ونجاحُ النشر لا يُثبتها (`/readyz` هنا 200 دائماً — صفّ `READYZ-RETURNS-200-WHEN-IT-REPORTS-NOT-READY-01`). | railway/decision | `{EV}` (`decision_service_staging`) | **open** (2026-09-30): قرارُ المالك — إلى `main` بعد **قراءة** حالة الهجرتين 033/034 من القاعدة: الهجرةُ أوّلاً لا الشيفرة، والقياسُ قبل الترتيب. |
| RAILWAY-DRAIN-ZERO-CUT-IN-FLIGHT-REQUESTS-01 | **أولويّة: تنظيف (دَينٌ مُغلَق).** لم تضبط أيُّ خدمةٍ `drainingSeconds`، وافتراضُ Railway صفر (SIGTERM ثمّ SIGKILL فوراً): كلُّ إعادة نشرٍ قطعت الطلباتِ الجارية — حدثٌ وقع في كلّ دمج، لا خطرٌ مستقبليّ. أثرُه المقيس ضئيلٌ لأنّ الحركة ضئيلة (واجهة الإنتاج 20 طلباً في 7 أيّام)، لا لأنّ القطع صحيح. | railway/deploy | `{EV}` (`config_changes_applied_owner_approved`) | **fixed** (2026-09-30، إعدادٌ بلا نشر): `drainingSeconds=20` على 11 خدمة. **شرطُ إعادة النظر:** إن تجاوزت الحركةُ 10 أضعاف القياس أعلاه يُراجَع الرقم ويُقاس أطولُ طلب. |
| FRONTEND-READYZ-IMPERSONATES-PLATFORM-READINESS-01 | **أولويّة: تنظيف.** `/readyz` في بوّابة الواجهة يُمرِّر إلى `/readyz` المنصّة — ليس جاهزيّةَ الواجهة بل جاهزيّةُ منصّةٍ مُنتحَلة؛ فجعلُه بوّابةَ نشر الواجهة يُجمِّد نشرها عند عطل المنصّة. | frontend/gateway | `frontend/nginx.conf:382` · `{EV}` (`frontend_healthcheck`) | **open** (2026-09-30): يُعاد كتابته ليعني ما يُسمّى به (إعدادُ nginx صالح · resolver مضبوط · أصولٌ ثابتة تُقدَّم) بلا اعتمادٍ على المنصّة؛ وحتّى ذلك يبقى فحصُ Railway على `/healthz`. |
| RAILWAY-OPERATIONS-OUTSIDE-MCP-REACH-01 | **أولويّة: قيدٌ تشغيليّ (ليس عطلاً).** أدواتُ Railway المتاحة للوكيل تقرأ كلَّ شيء وتضبط فحصَ الصحّة والتصريف والتداخل وأوامرَ الإقلاع وسياسةَ الإعادة وأنماطَ المراقبة والنسخَ المتماثلة والمتغيّرات وإعادةَ النشر وإنشاءَ الخدمات والأحجام والنطاقات والـwebhooks والتتبّع. **ولا تبلغ:** Wait for CI، والنسخَ الاحتياطيّ للأحجام (أخذاً وجدولةً واسترجاعاً)، وSQL على قاعدة البيانات (queue_v1 · فحوص ما قبل الترقية)، و`railway ssh`/`sandbox`/`connect`، وتغييرَ المصدر دون بناء كلّ البيئات؛ ووكيلُ Railway بلغ حدَّ الاستخدام. | railway/ops | `{EV}` (`production_gate.pending_owner_dashboard`) | **open** (2026-09-30): **قائمةُ اللوحة مغلقةٌ لا مفاجأةٌ شهريّة** — (١) Wait for CI · (٢) لقطةُ حجم `sahool-postgres` · (٣) وجهةُ webhook خارج Railway · (٤) تدقيقُ رايات staging والإنتاج (`SAHOOL_DEBUG` — لا يُسجِّل سطراً عند الإقلاع فلا يُقاس من السجلّ) · (٥) قيمُ المتغيّرات: أهي مراجعُ `${{{{…}}}}` أم ملصوقة (شرطُ بيئات PR) · (٦) تفعيلُ بيئات PR على `migrations/**` · (٧) قراءةُ حالة الهجرات في قاعدة الإنتاج للقراءة فقط (`decision_service_schema_migrations`، أو `/readyz` decision من داخل الشبكة) — لا أداةَ SQL ولا وصولَ للشبكة الخاصّة هنا · (٨) مفتاحُ بريد الإشعارات في Account Settings. **مقيسٌ بلا قراءة قيم:** دخولُ dev بلا كلمة مرور **غيرُ مُفعَّل** في البيئتين — `main.py:165` يُسجِّل تحذيراً عند تفعيله، وآخرُ إقلاعٍ للمنصّة (2026-09-28 12:47Z إنتاج · 12:48Z staging) بلا ذلك التحذير، والسجلُّ نفسه يُظهر `Application startup complete` في المدى ذاته (صفرٌ مُميَّزٌ عن غياب القياس). والنطاقُ العامّ لـstaging يبقى بقرار المالك: الخطرُ الرايةُ لا العنوان. |
| RAILWAY-LEFTOVER-SERVICES-01 | **أولويّة: تنظيف.** خدماتٌ متبقّية منشورة: في الإنتاج `wc005-postgres-live-proof` (يعمل) · `sahool-migrate` (بلا مصدر، europe-west4) · `sahool-raster-main-candidate` · `sahool-redis-state-0zaK` بجانب `sahool-redis-state` · `sahool-auth` القديم بجانب `sahool-auth-main`؛ وفي staging `platform-db-proof-20260927` وأخواتُها. | railway/ops | `{EV}` (`leftover_services`) | **open** (2026-09-30): قرارُ المالك — التنظيفُ بعد لقطةٍ للأحجام، لا قبلها. |
| RAILWAY-GATEWAY-HAS-NO-RATE-LIMIT-01 | **أولويّة: مهمّ.** بوّابةُ Railway العامّة (`frontend/nginx.conf`) بلا أيّ `limit_req`، وبوّابةُ v9 (`nginx/nginx.v9.conf`) فيها 32؛ حدودٌ على مستوى التطبيق في بعض موجِّهات المنصّة فقط. | frontend/gateway | `frontend/nginx.conf` (0 `limit_req`) · `nginx/nginx.v9.conf` (32) | **open** (2026-09-30): تغييرٌ صغير قابلٌ للاختبار في `frontend/nginx.conf`؛ يصل الإنتاجَ فيُدمَج بعد بوّابته. |
| NO-CONTINUOUS-EXTERNAL-MONITOR-01 | **أولويّة: مهمّ.** فحصُ صحّة Railway يعمل عند النشر وحده («Railway does not monitor the healthcheck endpoint after the deployment has gone live» — docs/deployments/healthchecks)، ولا webhook في المشروع. **وتصحيحٌ مقيس:** بريدُ تغيّر حالة النشر (ومنه البناءُ الفاشل) **اختياريّ** — «Enable email and in-app notifications in your Account Settings» (docs/overview/production-readiness-checklist) — فوجودُه غيرُ مضمون وحالتُه في اللوحة؛ ولا يكفي أنّ الانهيار بعد الإعادات يُرسل بريداً. والقاعدة: **برهانُ الوقوع من قناةٍ مستقلّة** — المراقِبُ خارج Railway (انقطاعُ Railway يمنع الإشعار بانقطاعه)، ولا يقيس النبضةَ بنبضةٍ أخرى من النظام نفسه. | railway/ops | `{EV}` · وثائق Railway (healthchecks · webhooks) | **open** (2026-09-30): قرارُ المالك — webhook إلى وجهةٍ خارج Railway (Slack/Discord)، ومراقبٌ خارجيّ واحد (UptimeRobot/Healthchecks.io) قبل أيّ بنيةٍ جديدة؛ لا خدمةَ مراقبةٍ على Railway. |
| POSTGRES-PATCH-PATH-FOR-CUSTOM-POSTGIS-IMAGE-01 | **أولويّة: مهمّ.** القاعدة على `postgis/postgis:15-3.4` (PG 15.8، وسمٌ متجمّد منذ 2024-10-14) — ولهذا لم تُرقَّع (CVE-2026-14666 مُصلَحٌ في 15.19). مقيسٌ من السجلّ: `15-3.5` = 15.13 (لا يبلغ الإصلاح)، `15-3.5-alpine` = 15.19 على musl (خطرُ ترتيب الفهارس النصّيّة)، و`postgres:15.19-bookworm` رسميٌّ على glibc. ميزاتُ Railway المُدارة (PITR · HA · الترقية بضغطة) للصورة الرسميّة وحدها. | railway/postgres | `{EV}` (`postgres_image`) | **open** (2026-09-30): المسارُ الأقلّ خطراً صورةٌ صغيرة من `postgres:15.19-bookworm` + PostGIS من مستودع PostgreSQL ثمّ `postgis_extensions_upgrade()`؛ قبلها فحوصُ SQL للقراءة (الترتيب · الإضافات · prepared xacts · md5 · slots · المساحة) ولقطةُ حجم. انقطاعٌ قصير لا مفرّ منه (حجم). يسبق تقويةَ SECURITY DEFINER. |
| BIDI-BASELINE-RAISED-BY-REGENERATION-01 | **أولويّة: تنظيف.** «الأساسُ يتقلّص ولا ينمو» كان وصفاً يقرؤه الفاحص وحده: `--generate` كان يكتب العدَّ الحاليّ أيّاً كان، فـ72→74 تمرّ بسطرٍ واحد. صنفُ M4: الحارسُ وصفَ الحالة ولم يصف الصواب. | ci/bidi | `scripts/ci/bidi_control_char_guard.py` (`generate`) · `tests_v9/test_bidi_control_char_guard.py` | **fixed** (`{G}`، 2026-09-30): التوليدُ يُخفِض ولا يرفع (`BaselineWouldGrow`)، وملفٌّ جديد لا يُقبَل بعلامة؛ أوّلُ توليدٍ وحده يكتب ما يجده. التكذيب: عكسُ التغيير ⇒ الاختباران الجديدان أحمران. **حدٌّ مُعلَن:** التحريرُ اليدويّ لملفّ الأساس ممكنٌ ويظهر في المراجعة. |
| RLM-72-IN-REGISTRY-CARRY-NO-MEANING-01 | **أولويّة: تنظيف (مؤجَّل بقرار).** في `sahool-brain/gaps/registry.md` اثنتان وسبعون علامة RLM (U+200F)، لا قلبَ اتّجاه بينها ولا واحدةٌ منها لازمةٌ للمعنى — «الموجودة الآن» لا «المشروعة». | brain | `sahool-brain/gaps/registry.md` · `docs/architecture/bidi_control_char_baseline.json` | **open** (2026-09-30، قرارُ المالك): لا تُمَسّ في هذه الموجة ولا تُضاف قاعدةٌ تُرخّصها. القرارُ المؤجَّل تحديدُ المواضع المشروعة: الحلُّ حينها حذفُ الحروف من داخل الأسطر إن أمكن بلا مساسٍ بالمعنى وبلا صدامٍ مع حارس الإضافة، أو الاعترافُ بأنّ الحارس يحرس شكلاً ويُعاد تعريفُه. |
| QDRANT-TENANT-FILTER-HAS-NO-PAYLOAD-INDEX-01 | **أولويّة: تنظيف.** عزلُ المستأجر في Qdrant صحيحٌ وفي الخادم (مرشِّحُ `metadata.tenant_id` داخل كلّ بحث)، لكن لا فهرسَ حمولةٍ عليه أصلاً (لا keyword ولا `is_tenant`): أداءٌ لا تسرّب. Qdrant غير منشورٍ على Railway. | rag/qdrant | `services/sahool-platform/core/rag/production_qdrant.py:1153` · `:1101` (`ensure_collection`) | **open** (2026-09-30). |
| REDIS-SHARED-PASSWORD-NO-ACL-01 | **أولويّة: تنظيف (قرارُ تصميم).** لا ACL في أيّ ملفّ compose: كلمةُ سرٍّ مشتركة، فأيُّ عميلٍ يستطيع `FLUSHALL`. النصفُ الثاني لإصلاح `REDIS-CLIENTS-WITHOUT-PASSWORD-LIGHT-UNIFIED-01`. | compose/redis | `docker-compose*.yml` (0 ACL) | **open** (2026-09-30): قرارُ المالك — مستخدمو ACL لكلّ خدمة. |
| OLLAMA-UNIFIED-PINNED-0-3-0-01 | **أولويّة: تنظيف.** `docker-compose.unified.yml` يثبّت `ollama/ollama:0.3.0` (مربوطاً بـ127.0.0.1)، وv9 على 0.32.5 بالبصمة. Ollama غيرُ منشورٍ على Railway. نسخةُ إصلاح CVE-2026-7482 لم تُتحقَّق (OSV وNVD محجوبان بسياسة الخروج). | compose/ollama | `docker-compose.unified.yml:394` | **open** (2026-09-30). |
| RAILWAY-BUILT-WITH-RAILPACK-DESPITE-DOCKERFILE-CONFIG-01 | **أولويّة: مهمّ.** **الصنف:** Railway يبني بـ**railpack** خدمةً مضبوطةً `builder: DOCKERFILE`، فيفشل البناءُ قبل أن يُلمَس الـDockerfile (`✖ Railpack could not determine how to build the app` ⇒ `railpack prepare exited with an error`). **المسحُ المقيس** (كلُّ خدمةٍ من المستودع في البيئتين، آخرُ بناءٍ فعليّ، 2026-09-30): الحالتان الوحيدتان `sahool-migrate-main` في **إعادتَي النشر** 2026-09-28 12:40Z (`600fa8bb` إنتاج · `90e48979` staging)؛ وبقيّةُ الموجة نفسها بُنيت بالـDockerfile. **ليس** المميِّزَ اسمُ المتغيّر `RAILWAY_DOCKERFILE_PATH` (موجودٌ في كلّ الخدمات عدا decision وكلّها نجحت) ولا إعادةُ النشر بذاتها. **والأثرُ في الإنتاج:** لا نشرَ ناجحاً حيّاً لـmigrate-main (آخرُ ناجح `5b5aec8c` أُزيل)، وكلُّ التزامٍ لاحق SKIPPED بأنماط المراقبة — فلن يُعاد بناؤه حتّى يمسّ التزامٌ `migrations/**` أو يُنشَر يدويّاً؛ وحالةُ هجرات الإنتاج لا تُثبَت من Railway: **يعمل، لا يُصلَح، لا يُراقَب.** | railway/build | `certification/evidence/railway_live_config_20260930.json` (`production_migrate_main`) · مسحُ البنّاء (28 نشراً) | **open** (2026-09-30): السببُ استدلالٌ لا برهان — الإعدادُ الفعّال للبناء لم يَحُلّ إلى الـDockerfile لحظةَ إعادة النشر (إعدادُ الخدمة عُدِّل عبر الزمن: Dockerfile الـauth في 09-19 ثمّ Dockerfile.migrate)؛ وتاريخُ الإعداد لا تُظهره الأدوات. قيمةُ `RAILWAY_DOCKERFILE_PATH` بندُ اللوحة (٥). والتشغيلُ يكتب قاعدةَ الإنتاج ⇒ بعد اللقطة وبقرار المالك. |
| MIGRATION-STATE-IN-PRODUCTION-IS-UNREAD-01 | **أولويّة: حرِج (قبل أيّ ترتيبٍ للهجرات، وأرخصُ من البوّابة).** لا صفَّ يستطيع اليوم أن يقول «طُبِّقت هجرةٌ» في الإنتاج: **المُهاجِرُ الرئيسيّ بلا سجلّ** — `migrations/apply_in_compose.sh` يُعيد تطبيقَ كلّ ما في `MANIFEST` في كلّ تشغيل (idempotent)، فلا جدولَ `schema_migrations` يُقرأ، وحالتُه تُستدَلّ من كائنات المخطَّط؛ ونشرُه في الإنتاج لم ينجح حيّاً (`RAILWAY-BUILT-WITH-RAILPACK-DESPITE-DOCKERFILE-CONFIG-01`). و**decision-service له سجلُّه** (`decision_service_schema_migrations`، `migration_runner.py:28`) ويعرضه `/readyz` (`migrations_current`/`pending_migrations`) — لكنّها بلا نطاقٍ عامّ، ونجاحُ نشرها لا يُثبت شيئاً لأنّ `/readyz` يُعيد 200 وإن قال degraded. | db/migrations | `migrations/apply_in_compose.sh:47-54` · `services/decision-service/migration_runner.py:28` · `services/decision-service/main.py:520-535` | **open** (2026-09-30، قاعدةُ المالك: من يقيس ≠ من يفعل): قراءةٌ مباشرة للقراءة فقط — لا تحتاج لقطةً لأنّها لا تكتب (اللقطةُ شرطُ التشغيل لا القياس). لا أداةَ في المتناول (لا SQL ولا شبكةً خاصّة) ⇒ بندُ اللوحة (٧). **ولا تُخطَّط الهجرةُ التالية قبلها.** |
| READYZ-RETURNS-200-WHEN-IT-REPORTS-NOT-READY-01 | **أولويّة: مهمّ.** فحصُ صحّة Railway يقرأ **رمزَ الحالة** لا الجسم: `/readyz` في decision-service يُعيد 200 دائماً وإن قال `"ready": false, "status": "degraded"` (هجراتٌ متأخّرة · SoR بلا قاعدة · توكنٌ مفقود)، و`/readyz` في tts-service يقول `"ready"` دائماً وإن سقط Redis. فبوّابةُ النشر عليهما فارغة — نفسُ صنف الحارس الذي يمرّ على ما وُجد لكشفه. (platform وauth يُعيدان 503 عند غياب القاعدة — البوّابةُ عليهما حقيقيّة.) | services/readiness | `services/decision-service/main.py:520-535` · `services/tts-service/routers/health.py` | **open** (2026-09-30): الإصلاحُ رمزُ الحالة يتبع الحكم (503 حين `ready=false`) مع اختبارٍ يُكذَّب؛ decision يصل الإنتاجَ فيُدمَج بعد بوّابته. |
| SAHOOL-DEBUG-FLAG-INVISIBLE-AT-RUNTIME-01 | **أولويّة: تنظيف (مؤجَّلُ الأثر).** `SAHOOL_DEBUG` لا يُسجِّل شيئاً عند الإقلاع — لا يُقرأ إلّا في تقرير جاهزيّةٍ إداريّ (`core/prod_readiness.py:85`) — فحالتُه في Railway لا تُقاس من السجلّ، بخلاف دخول dev (`main.py:165` يُسجِّل تحذيراً). | platform/config | `services/sahool-platform/core/prod_readiness.py:85` | **fixed in code — deferred effect** (`{L}`، 2026-09-30): سطرُ إقلاعٍ في `services/sahool-platform/api/routers/readiness.py` يُسجِّل الحالة (`SAHOOL_DEBUG=on/off`، لا قيمة). **يصير فعّالاً عند انتقال platform إلى `main`** (يُنشَر اليوم من فرعَي `deploy/*`)؛ **والمخرجُ ظهورُ السطر في سجلّ إقلاع المنصّة** — لا يُقرأ هذا الصفُّ مغلقاً قبل ذلك. |
| REPORTS-MUST-CITE-THIS-REPOSITORY-01 | **أولويّة: قاعدة.** مرّتين وصل تقريرٌ منظَّمٌ بجداول وأولويّاتٍ ومراجع **عن مشروعٍ آخر** (`rls_isolation_test.sql`/0009؛ ثمّ `retention_runs`/`intermodal`/`hermes-app`) — والشكلُ يوحي بأنّه فُحص. | process | هذا الصفّ · `sahool-brain/log.md` (2026-09-30) | **open — قاعدة** (2026-09-30، سمّاها المالك): **أيُّ تقريرٍ عن هذا المستودع يستشهد بـ`file:line` فيه، وإلّا فليس عنه.** والفالسيفير «صفرُ ملفّات» لكلّ مصطلحٍ فيه قبل أيّ عمل. صنفُ least-forgeable-input مطبَّقاً على التوثيق: ما لا يُشير إلى موضعٍ لا يُكذَّب، فلا يُصدَّق. |
"""

LOG = f"""## [2026-09-30] governance | بوّابةُ الإنتاج وخريطةُ Railway الحيّة: عشرين صفّاً بأولويّاتها (وصفُّ بناء Docker سُجِّل مع إصلاحه)، وحارسُ bidi يُخفِض ولا يرفع

**قراءة ثلاثة وكلاء بحث** (وثائق Railway الرسميّة · المجتمع · خريطة النشر الحيّ، للقراءة فقط) ثمّ تحقّقي بنفسي من كلّ ما صار صفّاً؛ والأدلّةُ في `{EV}` (أسماءُ متغيّراتٍ لا قيم). **بالأولويّة لا بالعدد:** حرِجة — `MIGRATION-STATE-IN-PRODUCTION-IS-UNREAD-01` (قراءةٌ قبل أيّ ترتيب هجرات، وأرخص) · `PRODUCTION-DEPLOYS-FROM-MAIN-WITHOUT-CI-GATE-01`؛ ومهمّ: `READYZ-RETURNS-200-WHEN-IT-REPORTS-NOT-READY-01` · `RAILWAY-BUILT-WITH-RAILPACK-DESPITE-DOCKERFILE-CONFIG-01` · `PLATFORM-DEPLOYED-FROM-STALE-BRANCHES-UNPATCHED-PYJWT-01` · `DECISION-SERVICE-STAGING-BEHIND-TENANT-BOUNDARY-FIXES-01` · `RAILWAY-GATEWAY-HAS-NO-RATE-LIMIT-01` · `NO-CONTINUOUS-EXTERNAL-MONITOR-01` · `POSTGRES-PATCH-PATH-FOR-CUSTOM-POSTGIS-IMAGE-01`؛ والباقي تنظيف: `RAILWAY-DRAIN-ZERO-CUT-IN-FLIGHT-REQUESTS-01` (fixed، دَينٌ مُغلَق بشرط 10×) · `FRONTEND-READYZ-IMPERSONATES-PLATFORM-READINESS-01` · `RAILWAY-OPERATIONS-OUTSIDE-MCP-REACH-01` · `RAILWAY-LEFTOVER-SERVICES-01` · `BIDI-BASELINE-RAISED-BY-REGENERATION-01` (fixed `{G}`) · `RLM-72-IN-REGISTRY-CARRY-NO-MEANING-01` · `QDRANT-TENANT-FILTER-HAS-NO-PAYLOAD-INDEX-01` · `REDIS-SHARED-PASSWORD-NO-ACL-01` · `OLLAMA-UNIFIED-PINNED-0-3-0-01` · `SAHOOL-DEBUG-FLAG-INVISIBLE-AT-RUNTIME-01` (مؤجَّلُ الأثر)؛ وقاعدة: `REPORTS-MUST-CITE-THIS-REPOSITORY-01`. **ونُفِّذ بقرار المالك بلا نشر:** فحصُ صحّة الإنتاج `/readyz` لـplatform وauth-main وauth، و`drainingSeconds=20` على 11 خدمة (pendingWork فارغ). **ورُدّ تقريرٌ من مشروعٍ آخر** (retention_runs · intermodal · hermes-app — صفرُ ملفّات هنا) واستُفيد منه بما قيس هنا: التخطّي يُقرأ نجاحاً (صارَ صفّاً)، والمراقبُ المستقلّ (صارَ قاعدةً في صفّ المراقبة).
"""

reg = root / "sahool-brain/gaps/registry.md"
text = reg.read_text(encoding="utf-8")
anchor = next(l for l in text.splitlines() if l.startswith("| TILER-IN-FIXED-AND-UNIFIED-HAS-NO-CONSUMER-AND-CANNOT-BUILD-01 |"))
assert text.count(anchor) == 1
text = text.replace(anchor, anchor + "\n" + ROWS.rstrip("\n"), 1)
assert ""+chr(0x200F)+"" not in ROWS and ""+chr(0x200E)+"" not in ROWS and ""+chr(0x200F)+"" not in LOG
reg.write_text(text, encoding="utf-8")
log = root / "sahool-brain/log.md"
lt = log.read_text(encoding="utf-8")
if not lt.endswith("\n"):
    lt += "\n"
log.write_text(lt + LOG, encoding="utf-8")
print("rows:", ROWS.count("\n| ") + 1)
