
ENABLE_PONYTAIL_GUARDRAILS = False
ENABLE_LEGACY_RECOMMENDATION_FALLBACK = True
REQUIRE_CANONICAL_FIELD_STATE = True
REQUIRE_HUMAN_REVIEW_FOR_PESTICIDES = True


# SAHOOL staged AI decision runtime flags
ENABLE_PONYTAIL_GUARDRAILS = False
ENABLE_LEGACY_RECOMMENDATION_FALLBACK = True
REQUIRE_CANONICAL_FIELD_STATE = True
REQUIRE_HUMAN_REVIEW_FOR_PESTICIDES = True
ENABLE_HUMAN_REVIEW_WORKFLOW = False
ENABLE_RAG_RERANKER = False
ENABLE_DECISION_AUTHORITY_CONTRACTS = True

GUARDRAIL_METRIC_NAMES = (
    "guardrail_trigger_total",
    "human_review_required_total",
    "recommendation_blocked_total",
    "evidence_missing_total",
)


# SAHOOL AI runtime progressive integration flags
ENABLE_PONYTAIL_GUARDRAILS = globals().get("ENABLE_PONYTAIL_GUARDRAILS", False)
ENABLE_LEGACY_RECOMMENDATION_FALLBACK = globals().get("ENABLE_LEGACY_RECOMMENDATION_FALLBACK", True)
REQUIRE_CANONICAL_FIELD_STATE = globals().get("REQUIRE_CANONICAL_FIELD_STATE", True)
REQUIRE_HUMAN_REVIEW_FOR_PESTICIDES = globals().get("REQUIRE_HUMAN_REVIEW_FOR_PESTICIDES", True)
ENABLE_HUMAN_REVIEW_WORKFLOW = globals().get("ENABLE_HUMAN_REVIEW_WORKFLOW", False)
ENABLE_JETSTREAM_RECOMMENDATION_EVENTS = globals().get("ENABLE_JETSTREAM_RECOMMENDATION_EVENTS", False)
ENABLE_RUNTIME_METRICS = globals().get("ENABLE_RUNTIME_METRICS", True)
ENABLE_RAG_QDRANT_INTEGRATION = globals().get("ENABLE_RAG_QDRANT_INTEGRATION", False)
