{{- range $name, $svc := .Values.workloads }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    {{- include "sahool.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  selector:
    app.kubernetes.io/component: {{ $name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http
{{- end }}
{{- end }}
