FROM postgres:16-alpine

RUN apk add --no-cache bash

WORKDIR /app
COPY migrations/ /migrations/
RUN chmod +x /migrations/apply_in_compose.sh

ENV MIG_DIR=/migrations
ENTRYPOINT ["bash", "/migrations/apply_in_compose.sh"]
