FROM public.ecr.aws/docker/library/postgres@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea

RUN apk add --no-cache bash

WORKDIR /app
COPY migrations/ /migrations/
RUN chmod +x /migrations/apply_in_compose.sh

ENV MIG_DIR=/migrations
ENTRYPOINT ["bash", "/migrations/apply_in_compose.sh"]
